### ISSUE TITLE
打开这个直接崩溃，怀疑是不是『"rtmp://192.168.31.134:1935/live/room"』需要不同环境特殊知道指定？

### ISSUE THREAD

**Issue by icebingo** [wei160liu20241028/CameraPush#1]
11-13 16:00:04.190 24477-24477/com.david.camerapush E/ffmpeg-c: Failed to open output：Connection timed out

**Comment by wei160liu20241028** [comment]
这个是我在自己的电脑上搭建的服务，要使用肯定要自己搭一个，然后修改代码中的IP才能使用
